app:
  name: "DOJ"
  mode: "dev"
  port: "8080"
  version: "v0.0.01"
log:
  level: "debug"
  filename: "doj.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 13306
  user: "root"
  password: "root"
  dbname: "DOJ"
  location: "Asia/Shanghai"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: "127.0.0.1"
  port: 16379
  db: 0
  pool_size: 100
  password: ""